import sys
import glob
import os.path

# import variables from other scons files
Import( '*' )
env = masterEnv.Clone()

env.AppendUnique( **mergeOptions( utdataflow_all_options, utcomponents_options, leap_options ) )

# create component libraries
comp_sources = globSourceFiles( '*.cpp' )

# compile components as shared libraries
setupComponentBuild(env, comp_sources, 'leapmotion')

sources = globSourceFiles( '*.cpp' )
headers = globSourceFiles( '*.h' )
createVisualStudioProject(env, sources, headers, 'leapMotion-Component')
